on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ğŸ§ Linux
            os: ubuntu-latest
            pnpm_command: 'build:linux'
            binary_path: dist/*.AppImage
            asset_name: zeroone.AppImage
          - name: ğŸªŸ Windows
            os: windows-latest
            pnpm_command: 'build:win'
            binary_path: dist/*.exe
            asset_name: zeroone.exe
          - name: ğŸ Mac
            os: macos-latest
            pnpm_command: 'build:mac'
            binary_path: dist/*.dmg
            asset_name: zeroone.dmg
    name: ${{ matrix.name }} Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: ğŸšš Checkout latest code
      uses: actions/checkout@v4

    - name: ğŸŸ© Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: âš¡ Setup pnpm
      uses: pnpm/action-setup@v4.0.0

    #TODO - Remove this once https://github.com/electron-userland/electron-builder/issues/6933#issuecomment-1213438889 is resolved
    - name: Tweak pnpm.cjs
      if: ${{ contains(matrix.os, 'windows') }}
      run: sed -i 's/\/usr\/bin\/env node/node/g' /c/Users/runneradmin/setup-pnpm/node_modules/.pnpm/pnpm@9.3.0/node_modules/pnpm/bin/pnpm.cjs
      shell: bash
    
    - name: ğŸ”¨ Build Project
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pnpm i
        pnpm ${{ matrix.pnpm_command }}

    - name: ğŸ“¦ Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.binary_path }}
permissions:
  contents: write